name: MazeShop
version: 1.0.0
main: Pixelis0P\MazeShop\MazeShop
api: 5.0.0
author: Pixelis0P & MazecraftMCN Team
description: A comprehensive shop plugin for PocketMine-MP with MazePay integration
website: https://github.com/Pixelis0P/MazeShop
depend: [MazePay]

permissions:
  mazeshop.command.shop:
    description: Allows usage of /shop command
    default: true
  
  mazeshop.command.shop.admin:
    description: Allows usage of /shop disable/enable and bypass shop disabled
    default: op
  
  mazeshop.command.sell:
    description: Allows usage of /sell command
    default: true