name: MazeShop
version: 1.0.0
main: PixelMCN\MazeShop\Main
api: 5.0.0
author: PixelMCN
description: Advanced shop and auction system with multi-level categories and economy integration
github: https://github.com/PixelMCN/MazeShop
website: https://mazecraftmc.fun
softdepend: [MazePay, BedrockEconomy]

permissions:
  mazeshop.use:
    description: Allow using shop commands
    default: true
  mazeshop.admin:
    description: Allow using shop admin commands
    default: op
  mazeshop.auction.use:
    description: Allow using auction commands
    default: true
  mazeshop.auction.admin:
    default: op
  mazeshop.category.edit:
    description: Allow editing shop categories
    default: op

