# MazeShop Configuration File
# Developed by PixelMCN

# GUI Settings
gui:
  # Shop GUI Type: "form" or "chest"
  shop-type: "chest"
  # Auction GUI Type: "form" or "chest"
  auction-type: "form"

# Currency Settings
currency:
  symbol: "$"
  name: "Money"

# Database Settings (MySQL only)
database:
  # Enable MySQL sync for shop items across servers
  enabled: false
  host: "localhost"
  port: 3306
  username: "root"
  password: ""
  database: "mazeshop"
  # Sync interval in seconds (how often to sync shop data)
  sync-interval: 300

# Shop Settings
shop:
  # Maximum items per page in GUI
  items-per-page: 45
  # Allow custom blocks from other plugins
  allow-custom-blocks: true

# Auction Settings
auction:
  # Minimum auction duration in seconds
  min-duration: 300
  # Maximum auction duration in seconds
  max-duration: 86400
  # Minimum starting bid
  min-starting-bid: 1
  # Auction fee percentage (0 = no fee)
  auction-fee: 5
  # Maximum active auctions per player
  max-auctions-per-player: 5

# Performance Settings
performance:
  # Enable async operations for database
  async-database: true
  # Cache shop data in memory
  cache-shop-data: true
